name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        env:
          WCA_CLIENT_ID: ${{secrets.WCA_ID}}
        run: |
          git config --global user.email "saransh.grover@stonybrook.edu"
          git config --global user.name "saranshgrover"
          git remote set-url origin https://${{secrets.DEPLOY_TOKEN}}@github.com/saranshgrover/WCARealTime.git
